import Head from 'next/head'
import Image from 'next/image'
import AddTaskButton from '../components/AddTaskButton'
import TodoModal from '../components/TodoModal'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ToDo App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

<AddTaskButton />
<TodoModal />
    </div>
  )
}
